### ISSUE TITLE
x-card里面的内容会跑到外面

### ISSUE THREAD

**Issue by coolarec** [benzBrake/XEditor#3]
x-card里面的内容如果有换行或者其他某些markdown语法会跑到折叠框外面去
![image](https://user-images.githubusercontent.com/46271219/152505015-5d56e680-ab85-4a84-a025-afd29f6ab43e.png)
![image](https://user-images.githubusercontent.com/46271219/152505020-2da9b7fc-9702-453d-812b-a0823fbdf37c.png)

另外如果有引用
>
>
的语句内容也会跑到外面,如图
![image](https://user-images.githubusercontent.com/46271219/152505322-bde547dd-d354-47f0-a076-64b4374a5e52.png)

**Comment by benzBrake** [comment]
目前确实短代码不能嵌套

**Comment by benzBrake** [comment]
你可以加群试用 XEditor 的 V2 版本 AAEditor，XEditor 我不打算更新了
